### ISSUE TITLE
setURLFromString should call setURL

### ISSUE THREAD

**Issue by jmburges** [chriswebb09/Musicly#3]
Just use setURL as the designated setter or w/e and have setURLFromString convert to URL and just call it

https://github.com/chriswebb09/Musicly/blob/c3dda24be52d0500970ec8388494345eaf4970ce/Musicly/Musicly/ApplicationSevices/Data/Local/Player.swift#L48-L55

**Comment by chriswebb09** [comment]
Fixed.
