### ISSUE TITLE
Bad Variable name: test

### ISSUE THREAD

**Issue by jmburges** [chriswebb09/Musicly#5]
https://github.com/chriswebb09/Musicly/blob/c3dda24be52d0500970ec8388494345eaf4970ce/Musicly/Musicly/ApplicationSevices/Data/Local/Player.swift#L88

Also I generally like using `self` whenever I access instance variable...even though you don't need it. Adds clarity IMHO

https://rainsoft.io/how-to-use-correctly-self-keyword-in-swift/

**Comment by jmburges** [comment]
Also it'd be nice if there was an error message here instead of just `return`

**Comment by chriswebb09** [comment]
Fixed
